### ISSUE TITLE
我在opensuse42.1 kde环境下，安装完之后，并没有运行

### ISSUE THREAD

**Issue by thedogb** [kuanghy/kreminder#1]
并没有自动运行，底栏也没有出现任何图标？

**Comment by kuanghy** [comment]
@thedogb 这个脚本依赖 pyqt4 和 apscheduler 模块，且只在 Ubuntu 下 Python2 环境测试通过。这个脚本是我刚接触 Python 时写的，也可能存在一些问题。有时间我将其重构一下。
